# Generated by Django 2.0.3 on 2018-04-02 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_claimed', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
        migrations.AddField(
            model_name='divisioninvite',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reggie.Invite'),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('event', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='divisioninvite',
            unique_together={('invite', 'division')},
        ),
    ]
