# Generated by Django 2.0.3 on 2018-04-02 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import league.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('header', models.ImageField(upload_to=league.models.Event.header_path)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_close', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar_background', models.CharField(max_length=7)),
                ('stream_link', models.URLField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Prep phase'), (1, 'Live event'), (2, 'Complete')], db_index=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_teams', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('team_count', models.PositiveSmallIntegerField(default=0)),
                ('open_invites', models.PositiveSmallIntegerField(default=0)),
                ('tournament_type', models.PositiveSmallIntegerField(choices=[(0, 'Single-elimination'), (1, 'Double-elimination')], default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDivisionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('event_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.EventDivision')),
            ],
        ),
        migrations.CreateModel(
            name='EventDivisionTeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_referee', models.BooleanField(default=False)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('event_division_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.EventDivisionTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to=league.models.Player.headshot_path)),
                ('number', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('usad_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('can_referee', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2019, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonDivisionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Season')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonDivisionTeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Player')),
                ('season_division_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.SeasonDivisionTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo', models.ImageField(upload_to=league.models.Team.logo_path)),
                ('cover', models.ImageField(upload_to=league.models.Team.cover_path)),
                ('location', models.CharField(max_length=255)),
                ('information', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Region')),
            ],
        ),
        migrations.AddField(
            model_name='seasondivisionteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Team'),
        ),
        migrations.AddField(
            model_name='eventdivisionteamplayer',
            name='season_division_team_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.SeasonDivisionTeamPlayer'),
        ),
        migrations.AddField(
            model_name='eventdivisionteam',
            name='season_division_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.SeasonDivisionTeam'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='seasondivisionteamplayer',
            unique_together={('player', 'season_division_team')},
        ),
        migrations.AlterUniqueTogether(
            name='seasondivisionteam',
            unique_together={('season', 'division', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='eventdivisionteamplayer',
            unique_together={('event_division_team', 'season_division_team_player')},
        ),
        migrations.AlterUniqueTogether(
            name='eventdivisionteam',
            unique_together={('event_division', 'season_division_team')},
        ),
        migrations.AlterUniqueTogether(
            name='eventdivision',
            unique_together={('event', 'division')},
        ),
    ]
