"""
Django settings for elite project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
	'.elite-dodgeball.com',
	'channels-backend',
]

ADMINS = (
	('Tim', 'tim@elite-dodgeball.com'),
)

if DEBUG:
	ALLOWED_HOSTS.append('localhost')
	ALLOWED_HOSTS.append('127.0.0.1')


# Application definition

INSTALLED_APPS = [
	'client.apps.ClientConfig',
	'league.apps.LeagueConfig',
	'reggie.apps.ReggieConfig',
	'tourf.apps.TourfConfig',
	'dashboard.apps.DashboardConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sitemaps',
	'django.contrib.sites',
	'django.contrib.humanize',
	'ckeditor',
	'channels',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, 'static/templates').replace('\\', '/'),
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'django.template.context_processors.i18n',
				'django.template.context_processors.media',
				'django.template.context_processors.static',
				'django.template.context_processors.tz',
				'django.template.context_processors.request',
				'elite.context_processors.global_vars',
			],
			'debug': True,
		},
	},
]

WSGI_APPLICATION = 'elite.wsgi.application'

SITE_ID = 1


# Auth
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth

LOGIN_URL = '/admin/login/'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': os.environ.get('DB_NAME'),
		'USER': os.environ.get('DB_USER'),
		'PASSWORD': os.environ.get('DB_PASSWORD'),
		'HOST': os.environ.get('DB_HOST', 'localhost'),
		'PORT': os.environ.get('DB_PORT', '5432'),
	}
}

if 'test' in sys.argv: # and not os.environ.get('CI'):
	DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'


# Channels
# https://channels.readthedocs.io/

ASGI_APPLICATION = 'elite.routing.application'

CHANNEL_LAYERS = {
	'default': {
		'BACKEND': 'channels_redis.core.RedisChannelLayer',
		'CONFIG': {
			'hosts': [
				'redis://%s:%s@%s:%s/%s' % (
					os.environ.get('REDIS_CLIENTID'),
					os.environ.get('REDIS_PASSWORD'),
					os.environ.get('REDIS_HOST', 'localhost'),
					os.environ.get('REDIS_PORT', '6379'),
					os.environ.get('REDIS_DB', '0')
				),
			],
		},
	},
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Internal IPs that get debug data
# https://docs.djangoproject.com/en/2.0/ref/settings/#internal-ips

INTERNAL_IPS = (
	'0.0.0.0',
	'127.0.0.1',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATICFILES_DIRS')

STATICFILES_DIRS = (
	os.environ.get('STATICFILES_DIRS', os.path.join(BASE_DIR, 'static')),
)


# Email settings
# https://help.mailgun.com/hc/en-us/articles/202464990-How-do-I-start-sending-email-

ANYMAIL = {
	'MAILGUN_API_KEY': os.environ.get('MAILGUN_API_KEY'),
	'MAILGUN_SENDER_DOMAIN': 'https://api.mailgun.net/v3/mg.elite-dodgeball.com',
}

EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
DEFAULT_FROM_EMAIL = 'Elite Dodgeball <contact@elite-dodgeball.com>'


# CKEditor
# https://pypi.python.org/pypi/django-ckeditor/5.4.0

CKEDITOR_CONFIGS = {
	'default': {
		'allowedContent': True,
		'removePlugins': 'stylesheetparser',
	}
}


# Stripe stuff
# https://stripe.com/docs/api/python

STRIPE_API_KEY = os.environ.get('STRIPE_API_KEY')
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')

STRIPE_SERVICE_FEE = 0.30
STRIPE_SERVICE_PERCENT = 0.029
