# Generated by Django 2.0.3 on 2018-04-04 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bracket_type', models.PositiveSmallIntegerField(choices=[(1, 'Round-robin'), (2, 'Winners bracket'), (3, 'Losers bracket'), (4, 'Finals bracket')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.EventDivision')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('round_number', models.PositiveSmallIntegerField(default=0)),
                ('game_number', models.PositiveSmallIntegerField(default=0)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Prep phase'), (1, 'Live game'), (2, 'Complete')], default=0)),
                ('top_wins', models.PositiveSmallIntegerField(default=0)),
                ('bottom_wins', models.PositiveSmallIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bottom_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.EventDivisionTeam')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tourf.Bracket')),
                ('loser_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tourf.Game')),
                ('top_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.EventDivisionTeam')),
                ('winner_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tourf.Game')),
            ],
        ),
        migrations.CreateModel(
            name='LivePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playing', models.BooleanField(default=False)),
                ('is_in', models.BooleanField(default=False)),
                ('event_division_team_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.EventDivisionTeamPlayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tourf.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='liveplayer',
            unique_together={('game', 'event_division_team_player')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('bracket', 'round_number', 'game_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('bracket_type', 'event_division')},
        ),
    ]
